# Generated by Django 5.2.1 on 2025-05-29 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='company_name',
            field=models.CharField(default='GOD', max_length=60),
        ),
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.URLField(blank=True, default='', null=True, verbose_name='Ссылка на сайт'),
        ),
        migrations.AddField(
            model_name='products',
            name='rating',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0),
        ),
    ]
